spring:
  profiles:
    active: prod
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  cache:
    cache-names: addr2coord, reverse_admin
    caffeine:
      spec: maximumSize=200000,expireAfterWrite=7d

jwt:
  secret: ${jwt.secret}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}

api:
  criminal:
    key: ${api.criminal.key}
    page-size: 1000
  emergencybell:
    key: ${api.emergencybell.key}
  vworld:
    key: ${api.vworld.key}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.messaging: DEBUG
    com.selfbell.safewalk.service.SafeWalkTrackService: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8080
