spring:
  datasource:
    url: jdbc:mysql://localhost:3306/selfbell
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
